services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/cleanfastapi
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    networks:
      - todoist_network
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_DB=cleanfastapi
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - todoist_network

volumes:
  postgres_data:
networks:
  todoist_network:
    driver: bridge